spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple Spin application written in (Tiny)Go."
name = "hello-example"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[component.hello]
source = "main.wasm"
[component.hello.build]
command = "tinygo build -target=wasip2 -gc=leaking -no-debug -wit-package ../../wit -wit-world fermyon:spin/http-trigger-rc20231018@2.0.0 -x -work -o main.wasm main.go"
